import { Inter } from "next/font/google";
import Navbar from "../components/Navbar";
import "./globals.css";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} dark:bg-[#0E0E0E]`}>
        <Providers>
          <div className="flex"> 
            <Navbar />
            <div className="flex-1">{children}</div> 
          </div>
        </Providers>
      </body>
    </html>
  );
}
