import { Inter } from "next/font/google";
import Navbar from '../components/Navbar'; // Adjust the import path as necessary
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
        <body className={`${inter.className} dark:bg-[#0E0E0E]`}>{children}</body>
    </html>
  );
}
